package com.thinkgem.jeesite.modules.session;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISessionManageBusinessService", targetNamespace = "http://business.ccpws.com/")
public interface ISessionManageBusinessService {

	/**
	 * 
	 * @param areaCode
	 * @param shortName
	 * @param callId
	 * @param password
	 * @return returns com.session.WssmLoginResultVo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "login", targetNamespace = "http://business.ccpws.com/", className = "com.session.Login")
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://business.ccpws.com/", className = "com.session.LoginResponse")
	public WssmLoginResultVo login(
			@WebParam(name = "callId", targetNamespace = "") String callId,
			@WebParam(name = "shortName", targetNamespace = "") String shortName,
			@WebParam(name = "password", targetNamespace = "") String password,
			@WebParam(name = "areaCode", targetNamespace = "") String areaCode);

	/**
	 * 
	 * @param sessionId
	 * @param callId
	 * @return returns com.session.WssmLogoffResultVo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "logoff", targetNamespace = "http://business.ccpws.com/", className = "com.session.Logoff")
	@ResponseWrapper(localName = "logoffResponse", targetNamespace = "http://business.ccpws.com/", className = "com.session.LogoffResponse")
	public WssmLogoffResultVo logoff(
			@WebParam(name = "callId", targetNamespace = "") String callId,
			@WebParam(name = "sessionId", targetNamespace = "") String sessionId);

}
